default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: rails_graphql_sample_development

test:
  <<: *default
  database: rails_graphql_sample_test

production:
  <<: *default
  database: rails_graphql_sample_production
